let level1 = createLevel1();

/**
 * Create the first level
 * @returns {Level}
 */
function createLevel1() {
    return new Level(
        [
            new BackgroundObject('./img/background/Layers/6.png', -720, 0),
            new BackgroundObject('./img/background/Layers/7.png', -720, 0),
            new BackgroundObject('./img/background/Layers/6.png', 0, 0),
            new BackgroundObject('./img/background/Layers/7.png', 0, 0),
            new BackgroundObject('./img/background/Layers/6.png', 720, 0),
            new BackgroundObject('./img/background/Layers/7.png', 720, 0),
            new BackgroundObject('./img/background/Layers/6.png', 1440, 0),
            new BackgroundObject('./img/background/Layers/7.png', 1440, 0),
            new BackgroundObject('./img/background/Layers/6.png', 2160, 0),
            new BackgroundObject('./img/background/Layers/7.png', 2160, 0),
            new BackgroundObject('./img/background/Layers/6.png', 2880, 0),
            new BackgroundObject('./img/background/Layers/7.png', 2880, 0),
            new BackgroundObject('./img/background/Layers/6.png', 3600, 0),
            new BackgroundObject('./img/background/Layers/7.png', 3600, 0)
        ],
        [
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new FrostCurse(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new DarkSamurai(),
            new Endboss()
        ],
        [
            new Tree('./img/background/Layers/8.png', -160, 0),
            new Tree('./img/background/Layers/8.png', 160, 0),
            new Tree('./img/background/Layers/8.png', 360, 0),
            new Tree('./img/background/Layers/8.png', 680, 0),
            new Tree('./img/background/Layers/8.png', 950, 0),
            new Tree('./img/background/Layers/8.png', 1200, 0),
            new Tree('./img/background/Layers/8.png', 1530, 0),
            new Tree('./img/background/Layers/8.png', 1700, 0),
            new Tree('./img/background/Layers/8.png', 2100, 0),
            new Tree('./img/background/Layers/8.png', 2430, 0),
            new Tree('./img/background/Layers/8.png', 2830, 0),
        ],
    )
}